version: "3.7"

services:
    # backend:
    #     image: microservice-python-flask:0.0.1
    #     restart: always
    #     ports:
    #         - 1080:5000
    #         #- 1443:443
    #     environment:
    #         EXAMPLE_ENV: prod
    #         DATABASE_URL: mysql+pymysql://myuser:password@mysql_db/mydb?charset=utf8mb4
    #     command: python manage.py run
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: '0.7'
    #                 memory: 150M
    #             reservations:
    #                 memory: 115M

    mysql_db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - 3306:3306
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: password
            #2Z4gT0zn2W
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 172M
                reservations:
                    memory: 128M

    phpmyadmin:
        depends_on:
            - mysql_db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8083:80
        environment:
            PMA_HOST: mysql_db
            MYSQL_ROOT_PASSWORD: password
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 172M
                reservations:
                    memory: 120M

volumes:
    db_data: